### ISSUE TITLE
cygfuse requires: cygwin pkg-config

### ISSUE THREAD

**Issue by AireagoirSteam** [mgeisert/cygfuse#3]
Hello there I downloaded the repository entered the directory and followed the instructions but get this output

$ make cygport
git clean -dfx
Removing cygfuse-2.8-1.i686/
Removing cygfuse-work.tar.gz
(\
        cd `git rev-parse --show-toplevel` &&\
        Stash=`git stash create` &&\
        git archive --prefix=cygfuse-work/ --format=tar.gz ${Stash:-HEAD}\
                > cygfuse-work.tar.gz\
)
CYGPORT_SRC_URI=cygfuse-work.tar.gz CYGPORT_SRC_DIR=cygfuse-work cygport cygfuse
.cygport download prep compile install package

> > > Preparing cygfuse-2.8-1.i686
> > > Unpacking source cygfuse-work.tar.gz
> > > Preparing working source directory
> > > Compiling cygfuse-2.8-1.i686
> > > make[1]: Entering directory '/home/Aireagoir/Downloads/cygfuse/cygfuse-2.8-1.i68
> > > 6/build'
> > > gcc -g -shared -o cygfuse-2.8.dll -Wl,--out-implib=libfuse-2.8.dll.a -I./inc/fus
> > > e cygfuse.c cygfuse-winfsp.c cygfuse-dokany.c
> > > sed "s/@Version@/2.8/g" fuse.pc.in > fuse.pc
> > > make[1]: Leaving directory '/home/Aireagoir/Downloads/cygfuse/cygfuse-2.8-1.i686
> > > /build'
> > > Installing cygfuse-2.8-1.i686
> > > /usr/bin/install -m0644 fuse.h /home/Aireagoir/Downloads/cygfuse/cygfuse-2.8-1.i
> > > 686/inst/usr/include/fuse/fuse.h
> > > /usr/bin/install -m0644 fuse_common.h /home/Aireagoir/Downloads/cygfuse/cygfuse-
> > > 2.8-1.i686/inst/usr/include/fuse/fuse_common.h
> > > /usr/bin/install -m0644 fuse_opt.h /home/Aireagoir/Downloads/cygfuse/cygfuse-2.8
> > > -1.i686/inst/usr/include/fuse/fuse_opt.h
> > > /usr/bin/install -m0644 cygfuse.h /home/Aireagoir/Downloads/cygfuse/cygfuse-2.8-
> > > 1.i686/inst/usr/include/fuse/cygfuse.h
> > > /usr/bin/install -m0755 cygfuse-2.8.dll /home/Aireagoir/Downloads/cygfuse/cygfus
> > > e-2.8-1.i686/inst/usr/bin/cygfuse-2.8.dll
> > > /usr/bin/install -m0644 libfuse-2.8.dll.a /home/Aireagoir/Downloads/cygfuse/cygf
> > > use-2.8-1.i686/inst/usr/lib/libfuse-2.8.dll.a
> > > /usr/bin/install -m0644 fuse.pc /home/Aireagoir/Downloads/cygfuse/cygfuse-2.8-1.
> > > i686/inst/usr/lib/pkgconfig/fuse.pc
> > > **\* Info: Skipping package doc installation per request
> > > Fixing symlinks:
> > > **\* Info: Skipping strip step per request.
> > > Preparing debuginfo source files:
> > > sort: cannot read: /home/Aireagoir/Downloads/cygfuse/cygfuse-2.8-1.i686/temp/.db
> > > gsrc.out: No such file or directory
> > > 
> > > Packaging cygfuse-2.8-1.i686
> > > Creating binary package(s)
> > > cygfuse-2.8-1.tar.xz
> > > usr/
> > > usr/bin/
> > > usr/bin/cygfuse-2.8.dll
> > > usr/include/
> > > usr/include/fuse/
> > > usr/include/fuse/cygfuse.h
> > > usr/include/fuse/fuse.h
> > > usr/include/fuse/fuse_common.h
> > > usr/include/fuse/fuse_opt.h
> > > usr/lib/
> > > usr/lib/libfuse-2.8.dll.a
> > > usr/lib/libfuse.dll.a
> > > usr/lib/pkgconfig/
> > > usr/lib/pkgconfig/fuse.pc

**\* Info: No debug files, skipping debuginfo subpackage

> > > Checking packages for missing or duplicate files
> > > 
> > > Creating source patches
> > >  0 files changed
> > > Creating source package
> > > cygfuse-2.8-1.src/
> > > cygfuse-2.8-1.src/cygfuse-work.tar.gz
> > > cygfuse-2.8-1.src/cygfuse.cygport
> > > 
> > > cygfuse requires: cygwin pkg-config

I checked for pkg-config and it is installed

then I try to run the tar command but it errors saying it doesn't exist

how would i install this in cygwin?

**Comment by billziss-gh** [comment]
It looks like the README has not been properly updated. The correct command should be:

```
tar -C/ -xaf cygfuse-2.8-1.x86_64/dist/cygfuse/cygfuse-2.8-1.tar.xz
```

**Comment by AireagoirSteam** [comment]
thank you

**Comment by mgeisert** [comment]
A belated thank-you to BZ for answering this.
