### ISSUE TITLE
What's relationship between this and winfsp

### ISSUE THREAD

**Issue by CMCDragonkai** [mgeisert/cygfuse#4]
A fuse package (somehow not packaged in the main packages) is located here http://www.secfs.net/winfsp/download/ and "cygfuse" is mentioned here: https://bitbucket.org/billziss/winfsp/src/c6ae62f3014cc0197ecc9342fd1bc35e646c2dea/opt/cygfuse/?at=master

**Comment by billziss-gh** [comment]
I am the author of WinFsp and original author of the cygfuse package.

Cygfuse was originally part of WinFsp. At some point I decided to submit the package to Cygwin, but there were complaints that the package was WinFsp specific. For this reason I took the original Cygfuse code and created a separate project with the goal to have a single FUSE package that supports all Windows user mode file system solutions. @mgeisert graciously agreed at the time to become the maintainer of this project.

**Comment by mgeisert** [comment]
A belated thank-you to BZ for answering this.
